Input_params:
  auth_code: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCcC1CTXAzeDFHa1EyNk1OTjBwdDFwbFBuOXlHRXE5aTE4ektMZG5wM2pna1pidTlaQVlwRV84VlRRU0FGRzB2bFFXcmtSdmxqdVFKT1lLdnNBVm5oQjF5cm4yY1NlX3hCVndOSjl4R3RpOTBFcjBKMD0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI4OTU4MzJlMDM0ZjQzNTVjMzRhZGY2OTM4NzNkMTMzNmM4OTc2NjkxOTNiYWE4OGQ2MzY2MTQwNSIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWEQyMjkxMSIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzc3OTQxMDAwLCJpYXQiOjE3Nzc4NjU1MTMsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc3Nzg2NTUxMywic3ViIjoiYWNjZXNzX3Rva2VuIn0.xaY2vHgw4TqNB3uYLKwmXm4vmI63L5EOsZMxqRfP_f4
  client_id: 9GMZCTCFZR-100
  grant_type: authorization_code
  last_login_time: '2026-05-04 09:01:51'
  redirect_uri: https://www.google.com
  response_type: code
  secret_key: VP4VZYSU96
  state: sample
data_loading_configs:
  symbol_list:
  - ADANIENT
  - ADANIPORTS
  - APOLLOHOSP
  - ASIANPAINT
  - AXISBANK
  - BAJAJ-AUTO
  - BAJAJFINSV
  - BAJFINANCE
  - BHARTIARTL
  - BPCL
  - BEL
  - BRITANNIA
  - CIPLA
  - COALINDIA
  - DRREDDY
  - EICHERMOT
  - ETERNAL
  - GRASIM
  - HCLTECH
  - HDFCBANK
  - HDFCLIFE
  - HEROMOTOCO
  - HINDALCO
  - HINDUNILVR
  - ICICIBANK
  - INDUSINDBK
  - INFY
  - ITC
  - JSWSTEEL
  - KOTAKBANK
  - LT
  - LTIM
  - MARUTI
  - NESTLEIND
  - NTPC
  - ONGC
  - POWERGRID
  - PAYTM
  - RELIANCE
  - RECLTD
  - RVNL
  - SBILIFE
  - SBIN
  - SHRIRAMFIN
  - SUNPHARMA
  - TATACONSUM
  - TMPV
  - TATASTEEL
  - TCS
  - TECHM
  - TITAN
  - TRENT
  - ULTRACEMCO
  - VEDL
  - WIPRO
data_saving:
  csv_path: D:\FM\compression_screener\artifacts\today_data.csv
  json_file_path: D:\FM\compression_screener\artifacts\hist_data.json
